/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IRowRatio".
 */
export type IRowRatio = ('50/50' | '33/66' | '66/33') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'about-page': AboutPage;
    'gallery-page': GalleryPage;
  };
  globalsSelect: {
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'gallery-page': GalleryPageSelect<false> | GalleryPageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  type: 'watercolour' | 'oil' | 'ceramics';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  layoutBlocks?:
    | (
        | {
            content?: {
              blocks?: (ISimpleContentBlock | ISliderCardBlock | ISliderWithCarouselBlock)[] | null;
            };
            section?: ISectionProps;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section';
          }
        | {
            content?: {
              ratio?: IRowRatio;
              block1?: (ISimpleContentBlock | ISliderCardBlock | ISliderWithCarouselBlock)[] | null;
              block2?: (ISimpleContentBlock | ISliderCardBlock | ISliderWithCarouselBlock)[] | null;
            };
            section?: ISectionProps;
            id?: string | null;
            blockName?: string | null;
            blockType: 'halfsection';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ISimpleContentBlock".
 */
export interface ISimpleContentBlock {
  title?: string | null;
  img?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  layout?: ('img-content' | 'content-img') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'SimpleContentBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ISliderCardBlock".
 */
export interface ISliderCardBlock {
  cards?:
    | {
        title?: string | null;
        description?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        img?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'SliderCardBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ISliderWithCarouselBlock".
 */
export interface ISliderWithCarouselBlock {
  cards?:
    | {
        title?: string | null;
        description?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        imgs?:
          | {
              img?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'SliderWithCarouselBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ISectionProps".
 */
export interface ISectionProps {
  variant?: ('full' | 'centered') | null;
  bg?: ('base' | 'green' | 'white' | 'greenMute') | null;
  blured?: boolean | null;
  zIndex?: number | null;
  topOffset?: number | null;
  bottomOffset?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page".
 */
export interface GalleryPage {
  id: number;
  layoutBlocks?:
    | (
        | {
            content?: {
              blocks?: ICarousel3D[] | null;
            };
            section?: ISectionProps;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section';
          }
        | {
            content?: {
              ratio?: IRowRatio;
              block1?: ICarousel3D[] | null;
              block2?: ICarousel3D[] | null;
            };
            section?: ISectionProps;
            id?: string | null;
            blockName?: string | null;
            blockType: 'halfsection';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ICarousel3D".
 */
export interface ICarousel3D {
  imgs?:
    | {
        img?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Carousel3dBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  layoutBlocks?:
    | T
    | {
        section?:
          | T
          | {
              content?:
                | T
                | {
                    blocks?:
                      | T
                      | {
                          SimpleContentBlock?: T | ISimpleContentBlockSelect<T>;
                          SliderCardBlock?: T | ISliderCardBlockSelect<T>;
                          SliderWithCarouselBlock?: T | ISliderWithCarouselBlockSelect<T>;
                        };
                  };
              section?: T | ISectionPropsSelect<T>;
              id?: T;
              blockName?: T;
            };
        halfsection?:
          | T
          | {
              content?:
                | T
                | {
                    ratio?: T;
                    block1?:
                      | T
                      | {
                          SimpleContentBlock?: T | ISimpleContentBlockSelect<T>;
                          SliderCardBlock?: T | ISliderCardBlockSelect<T>;
                          SliderWithCarouselBlock?: T | ISliderWithCarouselBlockSelect<T>;
                        };
                    block2?:
                      | T
                      | {
                          SimpleContentBlock?: T | ISimpleContentBlockSelect<T>;
                          SliderCardBlock?: T | ISliderCardBlockSelect<T>;
                          SliderWithCarouselBlock?: T | ISliderWithCarouselBlockSelect<T>;
                        };
                  };
              section?: T | ISectionPropsSelect<T>;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ISimpleContentBlock_select".
 */
export interface ISimpleContentBlockSelect<T extends boolean = true> {
  title?: T;
  img?: T;
  content?: T;
  layout?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ISliderCardBlock_select".
 */
export interface ISliderCardBlockSelect<T extends boolean = true> {
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        img?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ISliderWithCarouselBlock_select".
 */
export interface ISliderWithCarouselBlockSelect<T extends boolean = true> {
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        imgs?:
          | T
          | {
              img?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ISectionProps_select".
 */
export interface ISectionPropsSelect<T extends boolean = true> {
  variant?: T;
  bg?: T;
  blured?: T;
  zIndex?: T;
  topOffset?: T;
  bottomOffset?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page_select".
 */
export interface GalleryPageSelect<T extends boolean = true> {
  layoutBlocks?:
    | T
    | {
        section?:
          | T
          | {
              content?:
                | T
                | {
                    blocks?:
                      | T
                      | {
                          Carousel3dBlock?: T | ICarousel3DSelect<T>;
                        };
                  };
              section?: T | ISectionPropsSelect<T>;
              id?: T;
              blockName?: T;
            };
        halfsection?:
          | T
          | {
              content?:
                | T
                | {
                    ratio?: T;
                    block1?:
                      | T
                      | {
                          Carousel3dBlock?: T | ICarousel3DSelect<T>;
                        };
                    block2?:
                      | T
                      | {
                          Carousel3dBlock?: T | ICarousel3DSelect<T>;
                        };
                  };
              section?: T | ISectionPropsSelect<T>;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ICarousel3D_select".
 */
export interface ICarousel3DSelect<T extends boolean = true> {
  imgs?:
    | T
    | {
        img?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}